{
 "title": "Talaiot",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" },
   { "name": "db", "query": "SHOW DATABASES" },
   {
    "name": "rp",
    "query": "show retention policies on \"$db\""
   },
   {
    "name": "requestedTasks",
    "query": "show tag values on \"$db\" with key = \"requestedTasks\""
   },
   {
    "name": "performance_slice",
    "query": "osVersion,javaVmName,cpuCount,username,gradleVersion"
   }
  ]
 },
 "panels": [
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Builds",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Start time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"start\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "username",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT username FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "branch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT gitBranch FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "cacheRatio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cacheRatio FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"duration\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "gradleVersion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT gradleVersion FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"success\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "root project",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rootProject\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "requestedTasks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"requestedTasks\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "scan link",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"scanLink\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "os version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"osVersion\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='FROM_CACHE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Up-to-date tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='UP_TO_DATE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executed tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='EXECUTED'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "No source tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='NO_SOURCE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration [mean]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_requestedTasks]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"duration\") FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter GROUP BY requestedTasks, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Configuration [mean]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_requestedTasks]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"configuration\") FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter GROUP BY requestedTasks, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"rootNode\" = 'false' GROUP BY state,time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Task drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "P90 for $requestedTasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "alias": "[[tag_requestedTasks]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "P50 for $requestedTasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "alias": "[[tag_requestedTasks]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 50) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Max workers P90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Max Gradle workers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"maxWorkers\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task cache ratio P90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Max Gradle workers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"cacheRatio\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Xms P90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 33 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Xms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"javaXmsBytes\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Xmx P90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 33 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Xmx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"javaXmxBytes\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM available P90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 33 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"totalRamAvailableBytes\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU count P90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"cpuCount\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Performance slices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "repeat": "performance_slice" },
  {
   "title": "Duration of $requestedTasks [P90] by $performance_slice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_$performance_slice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY $performance_slice, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Performance slices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Duration of $requestedTasks [P90] by $performance_slice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_$performance_slice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY $performance_slice, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Performance slices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Duration of $requestedTasks [P90] by $performance_slice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_$performance_slice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY $performance_slice, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Performance slices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Duration of $requestedTasks [P90] by $performance_slice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_$performance_slice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY $performance_slice, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Performance slices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Duration of $requestedTasks [P90] by $performance_slice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_$performance_slice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY $performance_slice, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}