name: Run Gradle on PRs
on:
    pull_request:
    push:
        branches:
            - master
jobs:

    sample:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest,windows-latest]
                version: [11, 17, 21, 23, 25]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v5
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle build
              run: |
                  cd sample
                  ./gradlew assemble
                  ./gradlew assemble --configuration-cache
                  ./gradlew assemble --configuration-cache
