name: Run Gradle on PRs
on:
    pull_request:
    push:
        branches: [main]
jobs:
    ktlint:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [11]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle ktlint
              run:  ./gradlew ktlintCheck
    build:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [11]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle build
              run:  ./gradlew assemble

    pluginTest:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [11]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        services:
          docker:
            image: docker:19.03.12  # Specify Docker version
            options: --privileged  # Allow privileged mode for Docker
            ports:
                - 2375:2375  # Expose Docker daemon on port 2375
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle build
              run:  ./gradlew collectUnitTest

    publisherTest:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [11]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        services:
            docker:
                image: docker:19.03.12  # Specify Docker version
                options: --privileged  # Allow privileged mode for Docker
                ports:
                    - 2375:2375  # Expose Docker daemon on port 2375

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle build
              run: ./gradlew collectUnitTestLibs

    sample:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [11]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle build
              run: |
                  cd sample
                  ./gradlew assemble
