name: Running Samples in Gradle 8 and 9
on:
    pull_request:
    push:
        branches:
            - master
jobs:
    sample:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest,windows-latest]
                version: [17,21,25]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v5
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle build
              run: |
                  cd sample
                  ./gradlew assemble
                  ./gradlew assemble --configuration-cache
                  ./gradlew assemble --configuration-cache


    sample_gradle_8:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest,windows-latest]
                version: [11,15, 17,21]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v5
              with:
                  distribution:  ${{ matrix.vendor }}
                  java-version:  ${{ matrix.version }}

            - name: Execute Gradle build
              run: |
                  cd sample_gradle8
                  ./gradlew assemble
                  ./gradlew assemble --configuration-cache
                  ./gradlew assemble --configuration-cache
