name: Publish Snapshots

on:
    push:
        branches:
            - adding-jdk-11-min

jobs:
    publishing_snapshots:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v5
              with:
                  java-version: "11"
                  distribution: "zulu"

            - name: Set up JDK 17
              uses: actions/setup-java@v5
              with:
                  java-version: "17"
                  distribution: "zulu"

            - name: Publish snapshots
              run: ./gradlew publishAndReleaseToMavenCentral
              env:
                  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
                  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
                  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}


