name: Publish Snapshots

on:
    push:
        branches:
            - master

jobs:
    publishing_snapshots:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [17]
                vendor: [zulu]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.version }}
                  distribution: ${{ matrix.vendor }}

            - name: Publish snapshots
              run: ./gradlew publishAndReleaseToMavenCentral
              env:
                  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
                  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
                  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}


